apiVersion: v1
kind: Service
metadata:
  name: lootsheet
  namespace: lootsheet
  labels:
    app: lootsheet
spec:
  ports:
    - port: 8090
      targetPort: 8090
      name: http
      protocol: TCP
  selector:
    app: lootsheet

